### ISSUE TITLE
Duplicate Styles

### ISSUE THREAD

**Issue by jim-rosales** [Coderteen/prj-rev-bwfs-tea-cozy#5]
If you take a look at these CSS rules, you'll notice that they are all the same. Whenever you find yourself writing the same piece of code multiple times or copy and pasting it usually means there is a better way to apply the desired styles.

For example instead of using the original rules:
```CSS
.berryblitz
        {
          height:200px;
          width: 300px;
          margin-right: 20px;
        }


.spicedrum
        {
          height:200px;
          width: 300px;
          margin-right: 20px;
        }


.bedford
        {
          height:200px;
          width: 300px;
          margin-right: 20px;
        }


.myrtle
        {
          height:200px;
          width: 300px;
          margin-right: 20px;
        }


.donut
        {
          height:200px;
          width: 300px;
          margin-right: 20px;
        }
```

You could achieve the same result by doing the following:
```CSS
.images img {
  height:200px;
  width: 300px;
  margin-right: 20px;
}
```

This way every image that is a child of the `.images` class will inherit the appropriate height and width along with the desire margin-right.

5 lines of CSS vs. 30 lines. 

It takes a while and lots of practice to see when you could combine styles, but every time you are done writing your stylesheet take the time to analyze it to see if you find any rules that are repeated or that multiple elements share. If there is take the time to rewrite your CSS as it will make your life much easier down the road if you ever need to make changes. 

https://github.com/Coderteen/prj-rev-bwfs-tea-cozy/blob/fc5bdc17842a357c07bdf5a2937e3462d44c6e92/Tea%20Cozy/resources/css/style.css#L139-L172
